# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bjond-api 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "bjond-api".freeze
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Blake Rego".freeze]
  s.date = "2016-07-24"
  s.email = "blake.rego@bjondinc.com".freeze
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Manifest",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bjond-integration-gem.gemspec",
    "lib/bjond-api.rb",
    "lib/bjond-app-definition.rb",
    "lib/bjond-consequence.rb",
    "lib/bjond-event.rb",
    "lib/bjond-field.rb"
  ]
  s.homepage = "http://github.com/Bjond/bjond-integration-gem".freeze
  s.rubygems_version = "2.6.6".freeze
  s.summary = "Interface that facilitates communication with Bj\u{f6}nd servers.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<faraday>.freeze, [">= 0"])
    else
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<faraday>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<faraday>.freeze, [">= 0"])
  end
end

